# A static site
previewsEnabled: false
services:
  - type: web
    name: frontend
    env: static
    rootDir: ./frontend
    buildFilter:
      ignoredPaths:
        - frontend/pay_no_attention/*.txt
        - made/up/path/*
    buildCommand: yarn builds
    staticPublishPath: ./build
    autoDeploy: false
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: backend
          property: host
    routes:
      - type: rewrite
        source: /api/*
        destination: https://backend.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: backend
    autoDeploy: false
    env: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start

envVarGroups:
  - name: auth
    envVars:
      - key: AUTH_SECRET
        sync: false
