 # A static site
previewsExpireAfterDays: 1
previewsEnabled: true
services:
  - type: web
    pullRequestPreviewsEnabled: true
    name: frontend
    env: static
    rootDir: ./frontend
#    buildFilter:
#      ignoredPaths:
#      - frontend/pay_no_attention/*.txt
#      - test/ing/*
#      - made/up/path/*
    buildCommand: yarn build
    staticPublishPath: ./build
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://backend.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    plan: starter
    name: backend
    initialDeployHook: ./dephook.sh
    autoDeploy: true
    runtime: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: OTHER_IMPORTED_KEY
        fromService:
          type: web
          name: backend-slow-to-deply
          property: host
      - key: FORCE_SLOW_DEPENDENCY
        value: 'notused_updated_inPR'
      - fromGroup: testvargroup
  - type: web
    plan: starter
    name: backend-slower-to-deploy
    initialDeployHook: ./dephook.sh
    autoDeploy: true
    runtime: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: IMPORTED_KEY
        fromService:
          type: web
          name: backend
          property: host
envVarGroups:
  - name: testvargroup
    envVars:
      - key: syncfalse
        value: notgonnahappen
      - key: alsofalse
        sync: false
