 # A static site
previewsExpireAfterDays: 1
previewsEnabled: true
services:
  - type: web
    pullRequestPreviewsEnabled: false
    name: frontend
    branch: master
    env: static
    rootDir: ./frontend
#    buildFilter:
#      ignoredPaths:
#      - frontend/pay_no_attention/*.txt
#      - test/ing/*
#      - made/up/path/*
    buildCommand: yarn build
    staticPublishPath: ./build
    autoDeploy: true
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: backend
          property: host
      - fromGroup: testvargroup
    routes:
      - type: rewrite
        source: /api/*
        destination: https://backend.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    branch: master
    plan: starter
    name: backend
    initialDeployHook: ./dephook.sh
    autoDeploy: true
    runtime: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: FORCE_SLOW_DEPENDENCY
        value: 'notused_updated_inPR'
      - fromGroup: testvargroup
  - type: web
    branch: master
    plan: starter
    name: backend-slower-to-deploy
    initialDeployHook: ./dephook.sh
    autoDeploy: true
    runtime: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: OTHER_IMPORTED
        fromService:
          type: web
          name: backend
          envVarKey: FORCE_SLOW_DEPENDENCY
      - key: IMPORTED_KEY
        fromService:
          type: web
          name: backend
          property: host
envVarGroups:
  - name: testvargroup
    envVars:
      - key: syncfalse
        sync: false
      - key: altpreview
        value: dontshowup_and_falseit
        previewValue: falseit_and_dontshowup
      - key: regular
        value: regularvalue
    