 # A static site
previewsEnabled: true
services:
  - type: web
    name: frontend
    branch: master
    env: static
    rootDir: ./frontend
    buildFilter:
      ignoredPaths:
      - frontend/pay_no_attention/*.txt
      - made/up/path/*
    buildCommand: yarn build
    staticPublishPath: ./build
    autoDeploy: false
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: backend
          property: host
    routes:
      - type: rewrite
        source: /api/*
        destination: https://backend.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    branch: master
    name: backend
    autoDeploy: false
    env: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: DB_URL
        fromDatabase:
          name: eliphino
          property: connectionString
    
databases:
  - name: eliphino
    
envVarGroups:
  - name: auth
    envVars:
      - key: AUTH_SECRET
        sync: false
